name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: List contents of the root directory
      run: ls -al  # List contents of the root directory

    - name: List contents of the backend directory
      run: ls -al AzureProject/backend  # This should now point to the correct location of 'backend'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/AzureProject/backend/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and Test with Maven
      run: mvn clean install
      working-directory: ./AzureProject/backend  # Update the path to match the correct folder

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: AzureProject/backend/target/surefire-reports  # Correct path for test results
