name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/backend/pom.xml') }}  # Cache Maven dependencies using the correct path to pom.xml
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: List contents of the backend directory (for debugging)
      run: ls -al ./Backend  # List the contents of the 'backend' directory

    - name: Build and Test with Maven
      run: mvn clean install
      working-directory: ./Backend  # Specify 'backend' as the working directory for Maven

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./Backend/target/surefire-reports  # Path to the test results in 'backend'
